version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Build started on `date`
      - pwd
      - ls -all
      - cat /etc/os-release
      - whoami
      - cat /etc/pam.d/common-auth | grep auth
      - cat /etc/pam.d/common-auth | grep nullok_secure
      - sed -i 's/\(.*\)nullok_secure\(.*\)/\1nullok\2/' /etc/pam.d/common-auth
      - cat /etc/pam.d/common-auth | grep nullok
      - useradd ubuntu -s /bin/bash -G sudo -m
      - passwd -d ubuntu
      - groups ubuntu
      - exit
      - su - ubuntu
      - whoami
      - pwd
      - BUILD_PATH=$(pwd)
      - cd /home/
      - ls -all
      - cat /etc/passwd | grep ubuntu
      - cat /etc/shadow | grep ubuntu
      - cat /etc/group | grep ubuntu
      - cat /etc/gshadow | grep ubuntu
      - cd $BUILD_PATH
      - pwd
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Build started on `date`
      - cd bootstrap/
      - ls -all
      - sudo chmod +x bootstrap.sh
      - sudo chmod +x linux_bootstrap.sh
      - sudo ./bootstrap.sh
      - echo FINISH INSTALL!!!!
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pwd
      - cd ../
      - pwd
      - ls -all
      - export DISPLAY=:99.0
      - Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &
      - sleep 3
      - echo Start CI tests
      - sudo pipenv run iris firefox ci_tests/test_fake_keyboard_input.py -vk -i DEBUG
      - echo FINISH RUNNING TESTS
  post_build:
    commands:
      - echo Entered the post_build phase...
      - cd ~/.iris
      - ls -all
      - echo Build completed on `date`
