version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Build started on `date`
      - pwd
      - ls -all
      - whoami
      - apt-get install strace
      - python --version
      - useradd -s /bin/bash -d /home/ubuntu/ -m -G sudo ubuntu
      - grep ubuntu /etc/passwd
      - echo ubuntu:U6aMy0wojraho | chpasswd -e
      - grep ubuntu /etc/shadow
      - cd /home/
      - ls -all
      - su - ubuntu
      - whoami
      - su - ubuntu -c "echo SHOW_ME_SOMETHING"
      - strace su ubuntu
      - pwd
      - sudo apt-get update -y
      - sudo apt install -y xvfb
      - sudo apt install -y dbus-x11
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Build started on `date`
      - cd bootstrap/
      - ls -all
      - sudo chmod +x bootstrap.sh
      - sudo chmod +x linux_bootstrap.sh
      - sudo ./bootstrap.sh
      - pip install pipenv
      - sudo pipenv install
      - echo FINISH INSTALL!!!!
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pwd
      - cd ../
      - pwd
      - ls -all
      - export DISPLAY=:99.0
      - Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &
      - sleep 3
      - echo Start CI tests
      - sudo pipenv run iris firefox ci_tests/test_fake_keyboard_input.py -vk -i DEBUG
      - echo FINISH RUNNING TESTS
  post_build:
    commands:
      - echo Entered the post_build phase...
      - cd ~/.iris
      - ls -all
      - echo Build completed on `date`
